### ISSUE TITLE
Holograms causing server crash.

### ISSUE THREAD

**Issue by Bitmxp** [sainttx/Holograms#60]
When I remove the holograms folder, everything boots normally. When I use my holograms file, the server crashes. The errors are as follows:
```
17.07 20:43:18 [Server] Server thread/ERROR Encountered an unexpected exception
17.07 20:43:18 [Server] INFO net.minecraft.server.v1_14_R1.ReportedException: Exception ticking world
17.07 20:43:18 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1070) ~[spigot-1.14.3.jar:git-Spigot-595711b-e8b39d4]
17.07 20:43:18 [Server] INFO at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:396) ~[spigot-1.14.3.jar:git-Spigot-595711b-e8b39d4]
17.07 20:43:18 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:959) ~[spigot-1.14.3.jar:git-Spigot-595711b-e8b39d4]
17.07 20:43:18 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:804) [spigot-1.14.3.jar:git-Spigot-595711b-e8b39d4]
17.07 20:43:18 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
17.07 20:43:18 [Server] INFO Caused by: java.util.ConcurrentModificationException
17.07 20:43:18 [Server] INFO at java.util.HashMap$HashIterator.nextNode(HashMap.java:1445) ~[?:1.8.0_212]
17.07 20:43:18 [Server] INFO at java.util.HashMap$KeyIterator.next(HashMap.java:1469) ~[?:1.8.0_212]
17.07 20:43:18 [Server] INFO at java.lang.Iterable.forEach(Iterable.java:74) ~[?:1.8.0_212]
17.07 20:43:18 [Server] INFO at net.minecraft.server.v1_14_R1.ChunkMapDistance.a(SourceFile:119) ~[spigot-1.14.3.jar:git-Spigot-595711b-e8b39d4]
17.07 20:43:18 [Server] INFO at net.minecraft.server.v1_14_R1.ChunkProviderServer.tickDistanceManager(ChunkProviderServer.java:202) ~[spigot-1.14.3.jar:git-Spigot-595711b-e8b39d4]
17.07 20:43:18 [Server] INFO at net.minecraft.server.v1_14_R1.ChunkProviderServer.tick(ChunkProviderServer.java:278) ~[spigot-1.14.3.jar:git-Spigot-595711b-e8b39d4]
17.07 20:43:18 [Server] INFO at net.minecraft.server.v1_14_R1.WorldServer.doTick(WorldServer.java:257) ~[spigot-1.14.3.jar:git-Spigot-595711b-e8b39d4]
17.07 20:43:18 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1057) ~[spigot-1.14.3.jar:git-Spigot-595711b-e8b39d4]
17.07 20:43:18 [Server] INFO ... 4 more
17.07 20:43:18 [Server] Server thread/ERROR Cause of unexpected exception was
17.07 20:43:18 [Server] INFO java.util.ConcurrentModificationException: null
17.07 20:43:18 [Server] INFO at java.util.HashMap$HashIterator.nextNode(HashMap.java:1445) ~[?:1.8.0_212]
17.07 20:43:18 [Server] INFO at java.util.HashMap$KeyIterator.next(HashMap.java:1469) ~[?:1.8.0_212]
17.07 20:43:18 [Server] INFO at java.lang.Iterable.forEach(Iterable.java:74) ~[?:1.8.0_212]
17.07 20:43:18 [Server] INFO at net.minecraft.server.v1_14_R1.ChunkMapDistance.a(SourceFile:119) ~[spigot-1.14.3.jar:git-Spigot-595711b-e8b39d4]
17.07 20:43:18 [Server] INFO at net.minecraft.server.v1_14_R1.ChunkProviderServer.tickDistanceManager(ChunkProviderServer.java:202) ~[spigot-1.14.3.jar:git-Spigot-595711b-e8b39d4]
17.07 20:43:18 [Server] INFO at net.minecraft.server.v1_14_R1.ChunkProviderServer.tick(ChunkProviderServer.java:278) ~[spigot-1.14.3.jar:git-Spigot-595711b-e8b39d4]
17.07 20:43:18 [Server] INFO at net.minecraft.server.v1_14_R1.WorldServer.doTick(WorldServer.java:257) ~[spigot-1.14.3.jar:git-Spigot-595711b-e8b39d4]
17.07 20:43:18 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1057) ~[spigot-1.14.3.jar:git-Spigot-595711b-e8b39d4]
17.07 20:43:18 [Server] INFO at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:396) ~[spigot-1.14.3.jar:git-Spigot-595711b-e8b39d4]
17.07 20:43:18 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:959) ~[spigot-1.14.3.jar:git-Spigot-595711b-e8b39d4]
17.07 20:43:18 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:804) [spigot-1.14.3.jar:git-Spigot-595711b-e8b39d4]
17.07 20:43:18 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
17.07 20:43:18 [Server] Server thread/ERROR This crash report has been saved to: /./crash-reports/crash-2019-07-17_20.43.18-server.txt
17.07 20:43:18 [Server] Server thread/INFO Stopping server
17.07 20:43:18 [Server] Server thread/INFO [CitizensText] Disabling CitizensText v1.14
17.07 20:43:18 [Server] Server thread/ERROR Error occurred while disabling CitizensText v1.14 (Is it up to date?)
17.07 20:43:18 [Server] INFO java.lang.NullPointerException: null
17.07 20:43:18 [Server] INFO at fr.skytasul.citizenstext.CitizensText.saveDatas(CitizensText.java:117) ~[?:?]
17.07 20:43:18 [Server] INFO at fr.skytasul.citizenstext.CitizensText.onDisable(CitizensText.java:60) ~[?:?]
17.07 20:43:18 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[spigot-1.14.3.jar:git-Spigot-595711b-e8b39d4]
17.07 20:43:18 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:377) [spigot-1.14.3.jar:git-Spigot-595711b-e8b39d4]
17.07 20:43:18 [Server] INFO at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:437) [spigot-1.14.3.jar:git-Spigot-595711b-e8b39d4]
17.07 20:43:18 [Server] INFO at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:429) [spigot-1.14.3.jar:git-Spigot-595711b-e8b39d4]
17.07 20:43:18 [Server] INFO at org.bukkit.craftbukkit.v1_14_R1.CraftServer.disablePlugins(CraftServer.java:392) [spigot-1.14.3.jar:git-Spigot-595711b-e8b39d4]
17.07 20:43:18 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.stop(MinecraftServer.java:679) [spigot-1.14.3.jar:git-Spigot-595711b-e8b39d4]
17.07 20:43:18 [Server] INFO at net.minecraft.server.v1_14_R1.DedicatedServer.stop(DedicatedServer.java:681) [spigot-1.14.3.jar:git-Spigot-595711b-e8b39d4]
17.07 20:43:18 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:845) [spigot-1.14.3.jar:git-Spigot-595711b-e8b39d4]
17.07 20:43:18 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
17.07 20:43:18 [Server] Server thread/INFO [EssentialsSpawn] Disabling EssentialsSpawn v2.13.1
17.07 20:43:18 [Server] Server thread/INFO [BetterRTP] Disabling BetterRTP v2.8.2
```

The Holograms file is as follows:

```
holograms:
  lobby:
    location: world;36.792044805077936;88.0;9.46030658303521;33.900074;-232.37256
    lines:
    - Welcome to BitterCraft!
    - Hyperion Welcomes You! Be sure to read the rules!
  vote:
    location: world;23.489202798947474;83.0;-3.7821981300140166;55.199974;-356.39868
    lines:
    - Â§lVote For Us!
    - Â§bÂ§l/vote
    - In-Game Cash rewards for use in Admin Shop!
    - Get a key for the Daily Chest!
  north:
    location: world;19.45175995786165;85.0;-20.201642880067833;86.999954;-174.75171
    lines:
    - 'Â§l To Wilderness: North'
  west:
    location: world;5.491324677011082;85.0;-8.734811167254101;62.550007;-187.79785
    lines:
    - 'Â§l To Wilderness: South'
  choose:
    location: world;15.617034952477624;85.0;-11.979467491646083;33.299965;-217.04419
    lines:
    - Â§4Â§lChoose Your Direction
  north1:
    location: world;29.555650167971944;85.0;-47.27108460464578;51.749973;-137.83667
    lines:
    - Â§bÂ§lNorthern Wilderness
    - Â§lProceed with Caution!
  west1:
    location: world;-20.39682500704754;85.0;2.242872451556233;15.74999;-313.18872
    lines:
    - Â§bÂ§l Western Wilderness.
    - Â§lProceed With Caution!
  admin:
    location: world;-19.943423713467677;84.0;-22.305226584227494;12.150013;-257.55026
    lines:
    - 'Â§lAdmin Shop: Second Floor'
  shopb:
    location: world;-14.401959808632665;100.0;-22.413124410092838;26.999979;-354.43652
    lines:
    - Â§lAdmin Shop
    - Building Materials
  shopm:
    location: world;4.549158061024592;100.0;-1.7168983571574814;28.94997;-150.00244
    lines:
    - Â§lAdmin Shop
    - Mob Drops
  ores:
    location: world;4.811422074964926;100.0;-42.663376001882625;53.250008;-353.2398
    lines:
    - Â§lAdmin Shop
    - Ores/Minerals
  farmables:
    location: world;23.374758979925314;100.0;-22.452742671815386;-26.699995;-271.34082
    lines:
    - Â§lAdmin Shop
    - Farmables
  AShop:
    location: world;18.490428309662487;83.0;-8.756167313571451;29.1;-46.04883
    lines:
    - Â§lAdmin Shop Â§ron Second floor!
  rtp:
    location: world;21.536077075429613;83.0;2.4722069389105292;34.050102;-269.10135
    lines:
    - Â§lRandom Teleportation
    - Â§bJump in to begin your adventure!
  housing:
    location: world;29.500124846558382;83.0;-5.232195005343686;28.79996;-169.79065
    lines:
    - Â§lCommunity Area
    - Â§bTo Community Housing area
  housingwelcome:
    location: world;-289.498686719645;71.0;-710.8607568617937;60.299957;-176.25114
    lines:
    - Welcome to the
    - Â§lHousing District!
```
